def error_exit(message):
    logging.error(message)
    sys.exit(1)

